
const vatietyMap={
  hotVatiety:[
    { index: "Z", name: '中华田园猫' },
    { index: "L", name: '狸花猫' },
    { index: "J", name: '橘猫' },
    { index: "N", name: '奶牛猫' },
    { index: "H", name: '黑猫' },
    { index: "Y", name: '英短蓝白' },
    { index: "Y", name: '英短蓝猫' },
    { index: "Y", name: '英短银渐层' },
    { index: "Y", name: '英短金渐层' },
    { index: "B", name: '布偶猫' },
    { index: "B", name: '波斯猫' },
    { index: "J", name: '加菲猫' },
    { index: "F", name: '暹罗猫' },
    { index: "M", name: '美国短毛猫' },
    { index: "J", name: '金吉拉' },
    { index: "M", name: '缅因猫' },
  ],
  allVatiety:[
    { index: "A", name: '阿比西尼亚猫' },
    { index: "A", name: '埃及猫' },
    { index: "A", name: '奥西猫' },
    { index: "B", name: '白猫' },
    { index: "B", name: '巴厘猫' },
    { index: "B", name: '波米拉猫' },
    { index: "B", name: '波斯猫' },
    { index: "B", name: '伯曼猫' },
    { index: "B", name: '布偶猫' },
    { index: "D", name: '玳瑁猫' },
    { index: "D", name: '德文卷毛猫' },
    { index: "D", name: '东方猫' },
    { index: "D", name: '东奇尼猫' },
    { index: "E", name: '俄罗斯蓝猫' },
    { index: "H", name: '黑猫' },
    { index: "H", name: '哈瓦那棕猫' },
    { index: "H", name: '呵叻猫' },
    { index: "J", name: '加菲猫' },
    { index: "J", name: '加拿大无毛猫' },
    { index: "J", name: '金吉拉' },
    { index: "J", name: '橘猫' },
    { index: "L", name: '拉邦猫' },
    { index: "L", name: '褴褛猫' },
    { index: "L", name: '狸花猫' },
    { index: "L", name: '临清狮猫' },
    { index: "M", name: '马恩岛猫' },
    { index: "M", name: '曼基康猫' },
    { index: "M", name: '美国短毛猫' },
    { index: "M", name: '美国短尾猫' },
    { index: "M", name: '美国刚毛猫' },
    { index: "M", name: '美国卷耳猫' },
    { index: "M", name: '美国卷毛猫' },
    { index: "M", name: '孟加拉豹猫' },
    { index: "M", name: '孟买猫' },
    { index: "M", name: '缅甸猫' },
    { index: "M", name: '缅因猫' },
    { index: "N", name: '奶牛猫' },
    { index: "N", name: '挪威森林猫' },
    { index: "O", name: '欧洲缅甸猫' },
    { index: "R", name: '日本短尾猫' },
    { index: "R", name: '塞尔凯克卷毛猫' },
    { index: "S", name: '三花猫' },
    { index: "S", name: '沙特尔猫' },
    { index: "S", name: '斯芬克斯猫' },
    { index: "S", name: '苏格兰折耳猫' },
    { index: "S", name: '索马里猫' },
    { index: "T", name: '土耳其安哥拉猫' },
    { index: "T", name: '土耳其梵猫' },
    { index: "X", name: '西伯利亚森林猫' },
    { index: "X", name: '喜马拉雅猫' },
    { index: "X", name: '暹罗猫' },
    { index: "X", name: '新加坡猫' },
    { index: "Y", name: '异国短毛猫' },
    { index: "Y", name: '英国短毛猫' },
    { index: "Y", name: '英短蓝白' },
    { index: "Y", name: '英短蓝猫' },
    { index: "Y", name: '英短银渐层' },
    { index: "Y", name: '英短金渐层' },
    { index: "Y", name: '英国长毛猫' },
    { index: "Z", name: '中华田园猫' },
    { index: "Z", name: '重点色短毛猫' }
  ]
}



module.exports = vatietyMap;